import { Inter } from 'next/font/google'
import './globals.css'
import Script from 'next/script' // הוספנו את השורה הזו

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    // שינינו כאן לעברית ולימין-לשמאל
    <html lang="he" dir="rtl"> 
      <body className={inter.className}>
        {children}

        {/* הוספנו את הסקריפט כאן */}
        <Script src="/utm-capture.js" strategy="lazyOnload" />
      </body>
    </html>
  )
}